# Generated by Django 5.2.17 on 2026-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestion',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
